alter table DUMMY_COMPETITOR add constraint FK_DUMMY_COMPETITOR_ON_COUNTRY foreign key (COUNTRY_ID) references DUMMY_COUNTRY(ID);
create index IDX_DUMMY_COMPETITOR_ON_COUNTRY on DUMMY_COMPETITOR (COUNTRY_ID);
